/**
 * Realistic Data Scenarios
 * 
 * Tests the JSON Viewer with realistic, varied data generated by JSON Schema Faker.
 * This ensures the viewer handles real-world data structures correctly.
 */

import { test, expect } from '../../utils/base-test';
import { JsonViewerPage } from '../../page-objects/json-viewer-page';

test.describe('Anonymous User - Realistic Data Scenarios', () => {
  let viewerPage: JsonViewerPage;

  test.beforeEach(async ({ page }) => {
    viewerPage = new JsonViewerPage(page);
    await viewerPage.navigateToViewer();
  });

  test('should display realistic user profile with complete address', async ({ dataGenerator }) => {
    const user = dataGenerator.generateRealisticUser();
    const jsonString = JSON.stringify(user, null, 2);

    await viewerPage.inputJSON(jsonString);
    await viewerPage.waitForJSONProcessed();

    // Verify no errors
    expect(await viewerPage.hasJSONErrors()).toBe(false);

    // Verify structure
    const nodeCounts = await viewerPage.getNodeCounts();
    expect(nodeCounts.objects).toBeGreaterThan(2); // User + address + company
    
    // Take screenshot
    await viewerPage.takeScreenshot('realistic-user-profile');
  });

  test('should handle multiple realistic users in array', async ({ dataGenerator }) => {
    const users = dataGenerator.generateRealisticUsers(15);
    const jsonString = JSON.stringify(users, null, 2);

    await viewerPage.inputJSON(jsonString);
    await viewerPage.waitForJSONProcessed();

    // Verify array is processed
    const nodeCounts = await viewerPage.getNodeCounts();
    expect(nodeCounts.arrays).toBeGreaterThan(0);
    expect(nodeCounts.objects).toBeGreaterThan(15);

    // Verify no errors
    expect(await viewerPage.hasJSONErrors()).toBe(false);

    // Take screenshot
    await viewerPage.takeScreenshot('realistic-users-array');
  });

  test('should display e-commerce products with reviews and images', async ({ dataGenerator }) => {
    const products = dataGenerator.generateRealisticProducts(5);
    const jsonString = JSON.stringify(products, null, 2);

    await viewerPage.inputJSON(jsonString);
    await viewerPage.waitForJSONProcessed();

    // Verify complex product structure
    const nodeCounts = await viewerPage.getNodeCounts();
    expect(nodeCounts.objects).toBeGreaterThan(5);
    expect(nodeCounts.arrays).toBeGreaterThan(5); // Images, reviews, tags

    // Verify no errors
    expect(await viewerPage.hasJSONErrors()).toBe(false);

    // Take screenshot
    await viewerPage.takeScreenshot('realistic-products');
  });

  test('should handle API response with pagination metadata', async ({ dataGenerator }) => {
    const apiResponse = dataGenerator.generateRealisticAPIResponse();
    const jsonString = JSON.stringify(apiResponse, null, 2);

    await viewerPage.inputJSON(jsonString);
    await viewerPage.waitForJSONProcessed();

    // Verify API response structure
    const nodeCounts = await viewerPage.getNodeCounts();
    expect(nodeCounts.objects).toBeGreaterThan(1); // Response + pagination + data items
    expect(nodeCounts.arrays).toBeGreaterThan(0); // Data array

    // Verify no errors
    expect(await viewerPage.hasJSONErrors()).toBe(false);

    // Take screenshot
    await viewerPage.takeScreenshot('realistic-api-response');
  });

  test('should navigate deeply nested realistic structure', async ({ dataGenerator }) => {
    const nested = dataGenerator.generateRealisticDeepNesting();
    const jsonString = JSON.stringify(nested, null, 2);

    await viewerPage.inputJSON(jsonString);
    await viewerPage.waitForJSONProcessed();

    // Switch to tree view for better navigation
    await viewerPage.switchToTreeView();

    // Verify deep nesting
    const nodeCounts = await viewerPage.getNodeCounts();
    expect(nodeCounts.objects).toBeGreaterThan(5); // 5 levels deep

    // Test expand/collapse
    await viewerPage.expandAll();
    const expandedCount = await viewerPage.jsonNodes.count();
    expect(expandedCount).toBeGreaterThan(10);

    // Verify no errors
    expect(await viewerPage.hasJSONErrors()).toBe(false);

    // Take screenshot
    await viewerPage.takeScreenshot('realistic-deep-nesting');
  });

  test('should detect and display mixed data types correctly', async ({ dataGenerator }) => {
    const mixedTypes = dataGenerator.generateRealisticMixedTypes();
    const jsonString = JSON.stringify(mixedTypes, null, 2);

    await viewerPage.inputJSON(jsonString);
    await viewerPage.waitForJSONProcessed();

    // Verify mixed types are processed
    const nodeCounts = await viewerPage.getNodeCounts();
    expect(nodeCounts.arrays).toBeGreaterThan(5); // Multiple arrays of different types

    // Verify no errors
    expect(await viewerPage.hasJSONErrors()).toBe(false);

    // Take screenshot
    await viewerPage.takeScreenshot('realistic-mixed-types');
  });

  test('should display social media post with engagement metrics', async ({ dataGenerator }) => {
    const post = dataGenerator.generateSocialPost();
    const jsonString = JSON.stringify(post, null, 2);

    await viewerPage.inputJSON(jsonString);
    await viewerPage.waitForJSONProcessed();

    // Verify social post structure
    const nodeCounts = await viewerPage.getNodeCounts();
    expect(nodeCounts.objects).toBeGreaterThan(3); // Post + author + content + engagement

    // Verify no errors
    expect(await viewerPage.hasJSONErrors()).toBe(false);

    // Take screenshot
    await viewerPage.takeScreenshot('realistic-social-post');
  });

  test('should display financial transaction with metadata', async ({ dataGenerator }) => {
    const transaction = dataGenerator.generateTransaction();
    const jsonString = JSON.stringify(transaction, null, 2);

    await viewerPage.inputJSON(jsonString);
    await viewerPage.waitForJSONProcessed();

    // Verify transaction structure
    const nodeCounts = await viewerPage.getNodeCounts();
    expect(nodeCounts.objects).toBeGreaterThan(3); // Transaction + from + to + amount

    // Verify no errors
    expect(await viewerPage.hasJSONErrors()).toBe(false);

    // Take screenshot
    await viewerPage.takeScreenshot('realistic-transaction');
  });

  test('should display IoT sensor data with readings', async ({ dataGenerator }) => {
    const sensorData = dataGenerator.generateSensorData();
    const jsonString = JSON.stringify(sensorData, null, 2);

    await viewerPage.inputJSON(jsonString);
    await viewerPage.waitForJSONProcessed();

    // Verify sensor data structure
    const nodeCounts = await viewerPage.getNodeCounts();
    expect(nodeCounts.arrays).toBeGreaterThan(0); // Readings array
    expect(nodeCounts.objects).toBeGreaterThan(1);

    // Verify no errors
    expect(await viewerPage.hasJSONErrors()).toBe(false);

    // Take screenshot
    await viewerPage.takeScreenshot('realistic-sensor-data');
  });

  test('should display configuration object with all types', async ({ dataGenerator }) => {
    const config = dataGenerator.generateConfiguration();
    const jsonString = JSON.stringify(config, null, 2);

    await viewerPage.inputJSON(jsonString);
    await viewerPage.waitForJSONProcessed();

    // Verify configuration structure
    const nodeCounts = await viewerPage.getNodeCounts();
    expect(nodeCounts.objects).toBeGreaterThan(3); // Config + features + database + logging

    // Verify no errors
    expect(await viewerPage.hasJSONErrors()).toBe(false);

    // Take screenshot
    await viewerPage.takeScreenshot('realistic-configuration');
  });

  test('should handle large realistic dataset efficiently', async ({ dataGenerator }) => {
    const largeData = dataGenerator.generateLargeRealisticDataset();
    const jsonString = JSON.stringify(largeData, null, 2);

    const startTime = Date.now();

    await viewerPage.inputJSON(jsonString);
    await viewerPage.waitForJSONProcessed();

    const processingTime = Date.now() - startTime;

    // Verify large dataset is processed
    const nodeCounts = await viewerPage.getNodeCounts();
    expect(nodeCounts.total).toBeGreaterThan(50);

    // Should process reasonably fast (under 5 seconds)
    expect(processingTime).toBeLessThan(5000);

    // Verify no errors
    expect(await viewerPage.hasJSONErrors()).toBe(false);

    // Take screenshot
    await viewerPage.takeScreenshot('realistic-large-dataset');
  });

  test('should search within realistic user data', async ({ dataGenerator }) => {
    const users = dataGenerator.generateRealisticUsers(10);
    const jsonString = JSON.stringify(users, null, 2);

    await viewerPage.inputJSON(jsonString);
    await viewerPage.waitForJSONProcessed();

    // Search for email pattern
    await viewerPage.searchInJSON('@');

    // Wait for search to complete
    await viewerPage.page.waitForLoadState('networkidle');

    // Should find email addresses
    // (Exact verification depends on your search implementation)

    // Clear search
    await viewerPage.clearSearch();

    // Take screenshot
    await viewerPage.takeScreenshot('realistic-search-results');
  });

  test('should copy realistic JSON data', async ({ dataGenerator }) => {
    const product = dataGenerator.generateRealisticProduct();
    const jsonString = JSON.stringify(product, null, 2);

    await viewerPage.inputJSON(jsonString);
    await viewerPage.waitForJSONProcessed();

    // Copy JSON (if copy functionality exists)
    const hasCopyButton = await viewerPage.page.locator('button:has-text("Copy")').isVisible();
    
    if (hasCopyButton) {
      await viewerPage.page.locator('button:has-text("Copy")').click();
      
      // Wait for copy confirmation
      await expect(viewerPage.page.locator('text="Copied", .success, [role="alert"]').first()).toBeVisible();
    }

    // Verify no errors
    expect(await viewerPage.hasJSONErrors()).toBe(false);
  });

  test('should switch view modes with realistic data', async ({ dataGenerator }) => {
    const apiResponse = dataGenerator.generateRealisticAPIResponse();
    const jsonString = JSON.stringify(apiResponse, null, 2);

    await viewerPage.inputJSON(jsonString);
    await viewerPage.waitForJSONProcessed();

    // Test all view modes with realistic data
    const viewModeResults = await viewerPage.testAllViewModes();

    // Verify each mode works
    for (const result of viewModeResults) {
      expect(result.working).toBe(true);
    }

    // Take screenshot in each mode
    await viewerPage.takeScreenshot('realistic-data-all-modes');
  });
});

