#!/bin/bash
# Helper script to show what values need to be set in GitHub Secrets

echo "🔐 GitHub Secrets Configuration"
echo "================================"
echo ""
echo "Go to: https://github.com/$(git config --get remote.origin.url | sed 's/.*github.com[:/]\(.*\)\.git/\1/')/settings/secrets/actions"
echo ""
echo "Add these secrets:"
echo ""
echo "1. SSH_PRIVATE_KEY"
echo "   Value: (run: cat ~/.ssh/id_ed25519)"
echo "   ⚠️  Copy the ENTIRE key including BEGIN/END lines"
echo ""
echo "2. SERVER_HOST"
echo "   Value: 92.154.51.116"
echo ""
echo "3. SERVER_USER"
echo "   Value: joachim"
echo ""
echo "4. DEPLOY_PATH"
echo "   Value: ~/production/json-viewer-io"
echo ""
echo "5. APP_URL (optional)"
echo "   Value: https://json-viewer.io"
echo ""
echo "📝 Quick copy commands:"
echo ""
echo "   SERVER_HOST:"
echo "   92.154.51.116"
echo ""
echo "   SERVER_USER:"
echo "   joachim"
echo ""
echo "   DEPLOY_PATH:"
echo "   ~/production/json-viewer-io"
echo ""
echo "   APP_URL:"
echo "   https://json-viewer.io"
echo ""
